### ISSUE TITLE
Tail end error on CancerVar.py

### ISSUE THREAD

**Issue by bgold04** [WGLab/CancerVar#16]
Hello,

I get a multianno file, but I also get these messages.

```
NOTICE: Multianno output file is written to example/PRE_02_hg19.bin.sorted.withoutchr.hg19_multianno.txt
annovar_outfile is example/PRE_02_hg19.bin.sorted.withoutchr.hg19_multianno.txt
Traceback (most recent call last):
  File "CancerVar2.py", line 1900, in <module>
    main()
  File "CancerVar2.py", line 1866, in main
    sum1=check_genes(annovar_outfile)
  File "CancerVar2.py", line 652, in check_genes
    if sum==0 and re.findall('true',paras['otherinfo'], flags=re.IGNORECASE) :
KeyError: 'otherinfo'

```

**Comment by quanliustc** [comment]
which annovar version are you using？

**Comment by bgold04** [comment]
Thank you for getting me to update annovar and revert to the original unchanged CancerVar.

Still getting an error message, though, on CentOS 8.

```
NOTICE: Multianno output file is written to example/PRE_25_hg19.bin.sorted.withoutchr.hg19_multianno.txt
annovar_outfile is example/PRE_25_hg19.bin.sorted.withoutchr.hg19_multianno.txt
Traceback (most recent call last):
  File "CancerVar.py", line 1900, in <module>
    main()
  File "CancerVar.py", line 1866, in main
    sum1=check_genes(annovar_outfile)
  File "CancerVar.py", line 652, in check_genes
    if sum==0 and re.findall('true',paras['otherinfo'], flags=re.IGNORECASE) :
KeyError: 'otherinfo'
```
